on: [push]

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: Test Setup Ploigos Action
    steps:
      - name: Setup Ploigos
        id: setup-psr
        run: python -m pip install --upgrade git+https://github.com/ploigos/ploigos-step-runner.git@main
      - name: Run Ploigos
        id: run-psr
        run: psr --help

