on: [push]

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: Test Setup Ploigos Action
    steps:
      - name: Setup Ploigos
        id: setup-psr
        uses: dwinchell/setup-ploigos@main
      - name: Run Ploigos
        id: run-psr
        run: psr --help
